version: '3.8'
services:
  nginx:
      image: nginx:latest
      ports:
        - "5000:80"  # Expose nginx on port 5000 on the host
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - main
        - groove2groove_service
        - omnizart_service
        - rvc_service
        - spleeter_service
        - whisper_service
      networks:
        - app_network
  main:
    build: .
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    depends_on:
      - groove2groove_service
      - omnizart_service
      - rvc_service
      - spleeter_service
      - whisper_service
    networks:
      - app_network

  groove2groove_service:
    build: ./services/groove2groove
    develop:
      watch:
        - action: sync
          path: ./services/groove2groove
          target: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app_network

  omnizart_service:
    build: ./services/omnizart
    develop:
      watch:
        - action: sync
          path: ./services/omnizart
          target: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app_network

  rvc_service:
    build: ./services/rvc
    develop:
      watch:
        - action: sync
          path: ./services/rvc
          target: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app_network

  spleeter_service:
    build: ./services/spleeter
    develop:
      watch:
        - action: sync
          path: ./services/spleeter
          target: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app_network

  whisper_service:
    build: ./services/whisper
    develop:
      watch:
        - action: sync
          path: ./services/whisper
          target: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
